---
title: "Trabalho 2 - ME921"
author: "Ana Julia Cunha e Silva"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F, warning = F, error = F)
```

```{r bibliotecas}
library(readxl)
library(tidyverse)
library(covRobust)
library(mclust)

#para comparacao de metodos(comparar com kmeans)
library(factoextra)
library(cluster)
```

```{r carregando o banco e tratando}
dados <- read_xlsx("dados/all-weeks-globalNETFLIX.xlsx")
dados$category <- factor(dados$category)
dados$weekly_rank <- factor(dados$weekly_rank)
dados$cumulative_weeks_in_top_10 <- factor(dados$cumulative_weeks_in_top_10)

dados1 <- dados %>%
  select(!c(episode_launch_details,
            is_staggered_launch, season_title)) %>%
  filter(runtime >= 1) %>% 
  mutate(TituloQtd = log(str_width(show_title)),
         runtime = log(runtime)) %>%
  drop_na() %>% 
  group_by(show_title) %>% 
  filter(weekly_views == max(weekly_views)) %>%
  ungroup()

```

## Analisando com "ruido"
```{r estudo do banco}
dados1 <- dados1 %>%
  mutate(weekly_views = sqrt(weekly_views)) %>% 
  select(weekly_views, runtime, TituloQtd) 
pairs(dados1)

#BIC
fitBIC <- mclustBIC(dados1)
plot(fitBIC, xlab = "Número de Clusters", main = "Com Ruído")
fitBIC
```

```{r modelagem com ruido}
model1 <- Mclust(dados1, 4, modelNames = 'EVI')
plot(model1, what = "classification")
plot(model1, what = "uncertainty")
plot(model1, what = "density")

summary(model1)
uncerPlot(model1$z, ylab = "Incerteza")
```

## Analise lidando com os outliers

```{r estudo de perfil}
dados1 %>% mutate(Cluster = factor(model1$classification,
labels = c("C1", "C2", "C3", "C4"#, "C4", "C5"
           ))) %>%
pivot_longer(-Cluster, names_to = "Attribute",
values_to = "Values") %>%
ggplot(aes(x = Attribute, y = Values, fill = Cluster)) +
geom_boxplot() + theme_classic() + coord_flip() +
theme(legend.position = "bottom")+
  facet_wrap(~Attribute, scale = 'free')+labs(y = "")

```
# Tratamento do ruido

```{r tratamento de outlier}
nnve.out <- cov.nnve(dados1)

#BIC
fitBIC1 <-  mclustBIC(dados1, initialization = list(noise = (nnve.out$classification == 0)))

layout(matrix(1:2, ncol = 2)); plot(fitBIC, xlab = "Número de Clusters", ylab = "BIC (com ruído)"); plot(fitBIC1, xlab= "Número de Clusters", ylab = "BIC (com redução de ruído)")

#Modelo com reducao de ruido
model <- Mclust(dados1,
                initialization = list(noise = (nnve.out$classification==0)))
summary(model)
uncerPlot(model$z)

plot(model, what = "classification")
plot(model, what = "uncertainty")
plot(model, what = "density")
```

```{r perfil sem ruido}

dados1 %>% mutate(Cluster = factor(model$classification,
labels = c("Outliers", "C1", "C2", "C3", "C4", "C5"
           ))) %>%
pivot_longer(-Cluster, names_to = "Attribute",
  values_to = "Values") %>%
  ggplot(aes(x = Attribute, y = Values, fill = Cluster)) +
  geom_boxplot() + theme_bw() + coord_flip() +
  theme(legend.position = "bottom")+
  facet_wrap(~Attribute, scale = 'free')+
  labs(x = "")
```


## kmeans

```{r}
set.seed(236038)
fviz_nbclust(dados1, kmeans, method = "wss")+
  labs(title = "", x = "Número de Clusters",
       y = "Soma dos Quadrados Totais dos Clusters")

set.seed(236038)
fviz_nbclust(dados1, kmeans, method = "silhouette")+
  labs(title="", x = "Número de Clusters",
       y = "Largura Média da Silhueta")

modelokm <- pam(dados1, k = 2)
fviz_cluster(modelokm, data = dadosN0)+theme_classic()+
  labs(title = "")

```

